### ISSUE TITLE
Using cue-note with some non-English versions of Eos triggers a syntax error

### ISSUE THREAD

**Issue by johannesfelber** [douglasfinlay/cue-note#8]
**Description**
I'm using Eos with German language setting where the command line syntax is also localized.

**Steps to Reproduce**
1. Set Eos to German (or any other language where the syntax for cue notes differs, e. g. Italian)
2. Edit or delete notes via cue-note does not work (notes set from within Eos are displayed correctly)
3. In my example I try to set the cue label to "Live move"

**Expected behaviour**
Cue notes should be edited or removed as intended, even in the German version of Eos or other languages.

The correct command for e. g. German would be:
```
OSC            	  2023-12-04 12:18:00.357	[127.0.0.1:4735] RECV [OSC Packet] /eos/newcmd, Cue %1 / %2 Notizen %3 Enter(s), 1(s), 3(s), Live move(s)
```

**Eos Log**
```
OSC            	  2023-12-04 12:07:38.672	[127.0.0.1:4735] RECV [OSC Packet] /eos/newcmd, Cue %1 / %2 Notes %3 Enter(s), 1(s), 3(s), Live move(s)
Context        	  2023-12-04 12:07:38.672	Syntax: Cue 01 / 03 >>Notes - Syntaxfehler
```

**Environment**
 - OS : Windows 11 Pro
 - CueNote version:  0.3.0
 - Eos console version: 3.2.5 Build 13

Thanks!
Johannes

**Comment by douglasfinlay** [comment]
Hi Johannes,

Thanks for trying cue-note!

There is a more appropriate way to set notes via OSC which shouldn't suffer any localisation problems (something like `/eos/set/cue/<cue list number>/<cue number>/notes`). It's a simple fix so I hope to have the problem sorted in the next couple of days
