### ISSUE TITLE
Update usage README description for EOS versions v3.1x and earlier

### ISSUE THREAD

**Issue by cococow123** [douglasfinlay/cue-note#9]
I was trying to use this program with EOS version 3.0.2.6 with no luck given the usage instructions. Turns out some OSC options have changed since this version.

## To use CueNote with earlier versions, a couple of settings need to be adjusted:

In the EOS Shell configuration, under the Network tab, OSC must first be enabled
Then, OSC must be set to the **1.1 SLIP format.**
![image](https://github.com/douglasfinlay/cue-note/assets/16091192/ceaca163-39db-4782-b8bb-9063cf42f4e3)

Now open the console.

Go to **Setup > System > Show Control > OSC** and enable OSC.

Lastly, the OSC TCP Server Port **must** be set to 3037:
![image](https://github.com/douglasfinlay/cue-note/assets/16091192/7b21d238-20cc-4485-8c91-d3ddb7adbb1e)

Once I adjusted these options, CueNote successfully linked to my console and worked flawlessly.
Great program and I am excited to use it in the future!

**Comment by douglasfinlay** [comment]
Glad you managed to get it working! Thanks for sharing your config, I'll add your instructions to the readme.

CueNote was designed to communicate via the fixed _Third Party OSC_ port introduced in Eos 3.1.0. If there is a greater demand to support older software versions (< 3.1.0) I might look into adding a port and OSC version option to the connection screen.
